### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by beceluiz** [beceluiz/plan-to-read-booklist#1]

**Comment by faisalamin001** [comment]
Which library do you use for testing?
I'm available to write tests in Jest and React testing library
Thanks

**Comment by beceluiz** [comment]
@faisalamin001 
Hi, i like Jest and React testing library, vitest is good too.
feel free to write tests with library's you feel more comfortable since i didn't write any yet, Thank you!

**Comment by faisalamin001** [comment]
ok
