### ISSUE TITLE
add a loader

### ISSUE THREAD

**Issue by beceluiz** [beceluiz/plan-to-read-booklist#7]
add a loader before the db connect e shows the listed books

**Comment by faisalamin001** [comment]
Please give me permission to add the loader and push the code to this repo.
Thanks

**Comment by beceluiz** [comment]
@faisalamin001 
to add a loader and others features you can follow these steps:  <h2><a href="https://github.com/beceluiz/plan-to-read-booklist/blob/main/README.md">Contributing</a></h2>

**Comment by faisalamin001** [comment]
OK, thanks
